name: Render PDFs

on:
  workflow_dispatch:
    inputs:
      render-for-production:
        description: "Render for production"
        type: boolean
        default: false

jobs:
  render-pdfs:
    timeout-minutes: 5
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    env:
      PRINCE_DIR: ${{ github.workspace }}/.cache/prince
      PRINCE_FILE: prince_16.1-1_ubuntu24.04_amd64.deb

    name: Render PDF

    steps:
      - uses: actions/create-github-app-token@v3.0.0
        id: app-token
        with:
          app-id: ${{ vars.GHA_APP_ID }}
          private-key: ${{ secrets.GHA_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Create Prince directory
        run: mkdir -p "${{ env.PRINCE_DIR }}"
      - name: Restore Prince .deb cache
        id: prince-cache
        uses: actions/cache@v5
        with:
          path: ${{ env.PRINCE_DIR }}
          key: prince-${{ runner.os }}-${{ env.PRINCE_FILE }}
          restore-keys: |
            prince-${{ runner.os }}-
      - name: Download Prince .deb file on cache miss
        if: steps.prince-cache.outputs.cache-hit != 'true'
        run: curl -o "${{ env.PRINCE_DIR }}/${{ env.PRINCE_FILE }}" "https://www.princexml.com/download/${{ env.PRINCE_FILE }}"
      - name: Install Prince and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install "${{ env.PRINCE_DIR }}/${{ env.PRINCE_FILE }}"
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Render PDFs
        run: npm run render:pdf:local
        if: ${{ ! inputs.render-for-production }}
      - name: Render PDFs for production
        if: ${{ inputs.render-for-production }}
        run: npm run render:pdf
        env:
          DOCRAPTOR_API_KEY: ${{ secrets.DOCRAPTOR_API_KEY }}
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: render PDFs"
          file_pattern: "src/assets/downloads/*.pdf"
